# Libs

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
'''  
Pré-processamento sugerido:

Remoção de valores ambíguos como "Don’t know", "Refused to answer".

Eliminação de colunas com mais de 30% de valores faltantes.

Substituição de códigos como 88/888 por zero em variáveis de contagem de dias.

Aplicação de normalização MinMaxScaler.

Redução de colinearidade com análise de correlação (Pearson).

Binning em variáveis contínuas como altura e peso.

'''

'  \nPré-processamento sugerido:\n\nRemoção de valores ambíguos como "Don’t know", "Refused to answer".\n\nEliminação de colunas com mais de 30% de valores faltantes.\n\nSubstituição de códigos como 88/888 por zero em variáveis de contagem de dias.\n\nAplicação de normalização MinMaxScaler.\n\nRedução de colinearidade com análise de correlação (Pearson).\n\nBinning em variáveis contínuas como altura e peso.\n\n'

# Functions

In [3]:
# mapeando o diretório do projeto e do arquivo notebook 
diretorio_atual_projeto = os.getcwd() # Diretório atual do arquivo
notebook_dir_project_predict = os.path.normpath(f"{diretorio_atual_projeto}{os.sep}..{os.sep}..{os.sep}") + os.sep # Diretório do projeto
print(diretorio_atual_projeto)
print(notebook_dir_project_predict)

/home/ed/lgcm/projects/riskPredictionDeseases/dev/notebooks
/home/ed/lgcm/projects/riskPredictionDeseases/

In [4]:
def read_data_and_codebook(path_csv_data, path_csv_codebook):
    """
    Função para ler os dados e o código  .
    """
    # Lendo os dados
    df = pd.read_csv(path_csv_data)
    
    # Lendo o código
    codebook = pd.read_csv(path_csv_codebook)
    
    return df, codebook

# transformar os dados categorizados como dont know ou refused em NaN
def transform_dont_know_refused_to_nan(df):
    """
    Função para transformar os dados categorizados como dont know ou refused em NaN
    """
    # Transformando os dados categorizados como dont know ou refused em NaN
    df = df.replace({'dont know': np.nan, 'refused': np.nan})
    
    return df

# retirar as colunas com mais de 30% de missing data conforme artigo
def remove_columns_with_missing_data(df, threshold=0.3):
    """
    Função para remover colunas com mais de 30% de missing data
    """
    # Calculando o percentual de missing data
    missing_data = df.isnull().mean()
    
    # Removendo as colunas com mais de 30% de missing data
    df = df.loc[:, missing_data < threshold]
    
    return df

# Scripts

Ler o codebook e o respectivo dado

In [15]:
# precisaremos implementar a metodologia descrita no artigo gerando assim um primeiro dataset para treinamento
# ler o csv do dado bruto e do codebook para efetuar as transformações
raw_data_brfss = os.path.normpath(f"{notebook_dir_project_predict}{os.sep}data{os.sep}intermediate{os.sep}brfss_2023.csv")
codebook_file = os.path.normpath(f"{notebook_dir_project_predict}{os.sep}data{os.sep}intermediate{os.sep}2023{os.sep}brfss_2023_variaveis_expandidas_translated.csv")

df_2023 , codebook_2023 = read_data_and_codebook(raw_data_brfss, codebook_file)
# df_2023

In [23]:
codebook_2023

,Label,Section Name,Section Number,Question Number,Column,Type of Variable,SAS Variable Name,Question Prologue,Question,Value,Value Label,Frequency,Percentage,Weighted Percentage,label_translate,section_name_translate,question_translate,value_label_translate
0,State FIPS Code,Record Identification,0.0,1,1-2,Num,_STATE,NaN,State FIPS Code,1,Alabama,"4,362",1.01,1.58,Código de FIPS do estado,Identificação de registro,Código de FIPS do estado,Alabama
1,State FIPS Code,Record Identification,0.0,1,1-2,Num,_STATE,NaN,State FIPS Code,2,Alaska,"5,525",1.28,0.22,Código de FIPS do estado,Identificação de registro,Código de FIPS do estado,Alasca
2,State FIPS Code,Record Identification,0.0,1,1-2,Num,_STATE,NaN,State FIPS Code,4,Arizona,"12,036",2.78,2.31,Código de FIPS do estado,Identificação de registro,Código de FIPS do estado,Arizona
3,State FIPS Code,Record Identification,0.0,1,1-2,Num,_STATE,NaN,State FIPS Code,5,Arkansas,"5,351",1.23,0.94,Código de FIPS do estado,Identificação de registro,Código de FIPS do estado,Arkansas
4,State FIPS Code,Record Identification,0.0,1,1-2,Num,_STATE,NaN,State FIPS Code,6,California,"11,976",2.76,12.18,Código de FIPS do estado,Identificação de registro,Código de FIPS do estado,Califórnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1891,Always Wear Seat Belts,Calculated Variables,NaN,2,2109,Num,_RFSEAT3,NaN,Always Wear Seat Belts Calculated Variable,2,Don't Always Wear Seat Belt,"50,738",11.71,10.99,Sempre use cintos de segurança,Variáveis ​​calculadas,Sempre use cintos de segurança variável calculada,Nem sempre use cinto de segurança
1892,Always Wear Seat Belts,Calculated Variables,NaN,2,2109,Num,_RFSEAT3,NaN,Always Wear Seat Belts Calculated Variable,9,Don't know/Not Sure Or Refused/Missing,"31,505",7.27,8.70,Sempre use cintos de segurança,Variáveis ​​calculadas,Sempre use cintos de segurança variável calculada,Não sei/não tenho certeza ou recusou/ausente
1893,Drinking and Driving,Calculated Variables,NaN,3,2110,Num,_DRNKDRV,NaN,Drinking and Driving (Reported having driven ...,1,Have driven after having too much to drink,"6,192",1.43,1.36,Bebendo e dirigindo,Variáveis ​​calculadas,Beber e dirigir (relatou ter dirigido pelo men...,Dirigiram depois de beber muito
1894,Drinking and Driving,Calculated Variables,NaN,3,2110,Num,_DRNKDRV,NaN,Drinking and Driving (Reported having driven ...,2,Have not driven after having too much to drink,"205,541",47.43,45.81,Bebendo e dirigindo,Variáveis ​​calculadas,Beber e dirigir (relatou ter dirigido pelo men...,Não dirigiram depois de beber muito
1895,Drinking and Driving,Calculated Variables,NaN,3,2110,Num,_DRNKDRV,NaN,Drinking and Driving (Reported having driven ...,9,Don't know/Not Sure/Refused/Missing,"221,590",51.14,52.83,Bebendo e dirigindo,Variáveis ​​calculadas,Beber e dirigir (relatou ter dirigido pelo men...,Não sei/não tenho certeza/recusado/ausente

In [ ]:
# variável e índice para manter 
'''   
_STATE: [todas],
FMONTH: [todas],
IDATE: [todas],

'''

In [ ]:
'''       
No codebook,
SAS Variable Name - Coluna do Dado bruto 
Value - Valor no dado bruto
Value Label - Descrição do valor no dado bruto

'''

In [ ]:


def mapear_colunas_para_rotulo(df_brfss, codebook_df, sufixo='_map'):
    """
    Substitui colunas do DataFrame por versões mapeadas com rótulos do codebook.
    A coluna original é excluída e substituída por uma nova com sufixo (default: _map).
    Se o valor não for mapeável, mantém o valor original (sem 'Desconhecido').

    Parâmetros:
        df_brfss (pd.DataFrame): dados originais
        codebook_df (pd.DataFrame): DataFrame do codebook com 'SAS Variable Name', 'Value', 'Value Label'
        sufixo (str): sufixo para a nova coluna (default: '_map')

    Retorno:
        pd.DataFrame com colunas mapeadas
    """
    def limpar_valor(v):
        if pd.isna(v):
            return "BLANK"
        try:
            return str(int(v))  # converte 1.0 → '1'
        except:
            return str(v).strip()

    df_resultado = df_brfss.copy()
    colunas_mapeadas = {}

    for coluna in df_brfss.columns:
        try:
            # Extrai mapeamentos apenas para a variável atual
            codebook_var = codebook_df[codebook_df['SAS Variable Name'] == coluna]
            codebook_var = codebook_var.dropna(subset=['Value'])

            if codebook_var.empty:
                continue

            # Cria o dicionário de mapeamento
            mapa_valores = dict(zip(
                codebook_var['Value'].astype(str).str.strip(),
                codebook_var['Value Label']
            ))

            if not mapa_valores:
                continue

            # Aplica mapeamento apenas onde existir valor no dicionário
            serie_convertida = df_brfss[coluna].apply(limpar_valor)
            serie_mapeada = serie_convertida.apply(lambda x: mapa_valores.get(x, x))  # mantém valor original se não estiver no dicionário
            colunas_mapeadas[coluna + sufixo] = serie_mapeada

        except Exception as e:
            print(f"Erro ao mapear coluna '{coluna}': {e}")
            continue

    # Cria DataFrame com as colunas mapeadas
    df_mapeadas = pd.DataFrame(colunas_mapeadas)

    # Remove colunas originais que foram mapeadas
    colunas_para_remover = [col.replace(sufixo, '') for col in df_mapeadas.columns]
    df_resultado = df_resultado.drop(columns=colunas_para_remover)

    # Junta com colunas mapeadas
    df_resultado = pd.concat([df_resultado, df_mapeadas], axis=1)

    return df_resultado

# lista de colunas onde devemos retirar da string os seguintes caracteres "b'" di começo e "'" no final # IDATE IMONTH IDAY IYEAR
# IDATE IMONTH IDAY IYEAR
def limpar_colunas_data(df):
    """
    Função para limpar as colunas de data do DataFrame
    """
    # Limpando as colunas
    df['IDATE'] = df['IDATE'].str.replace("b'", "").str.replace("'", "")
    df['IMONTH'] = df['IMONTH'].str.replace("b'", "").str.replace("'", "")
    df['SEQNO'] = df['SEQNO'].str.replace("b'", "").str.replace("'", "")
    # df['IDAY'] = df['IDAY'].str.replace("b'", "").str.replace("'", "")
    # df['IYEAR'] = df['IYEAR'].str.replace("b'", "").str.replace("'", "")
    
    return df

# faremos uma lista de colunas que serão ignoradas pois todos os dados são o mesmo valor ou nulo e são dados de identificação de amostra

## 1 Dado bruto mapeado para exploração

In [19]:
df_2023_to_treat = df_2023.copy()
df_cleaned_date = limpar_colunas_data(df_2023_to_treat)

df_map = mapear_colunas_para_rotulo(df_cleaned_date, codebook_2023)
df_map.to_csv(f"{notebook_dir_project_predict}{os.sep}data{os.sep}intermediate{os.sep}2023{os.sep}brfss_2023_map.csv")
df_map

,LNDSXBRT,CELSXBRT,BIRTHSEX,TRNSGNDR,USEMRJN4,RCSGEND1,RCSXBRTH,_STATE_map,FMONTH_map,IDATE_map,...,DROCDY4__map,_RFBING6_map,_DRNKWK2_map,_RFDRHV8_map,_FLSHOT7_map,_PNEUMO3_map,_AIDTST4_map,_RFSEAT2_map,_RFSEAT3_map,_DRNKDRV_map
0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Alabama,January,3012023,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,NoNotes: AGE >=65 and FLUSHOT7 = 2,NoNotes: AGE >= 65 and PNEUVAC4 = 2,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
1,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Alabama,January,1062023,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,YesNotes: AGE >=65 and FLUSHOT7 = 1,YesNotes: AGE >= 65 and PNEUVAC4 = 1,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
2,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Alabama,January,3082023,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,YesNotes: AGE >=65 and FLUSHOT7 = 1,YesNotes: AGE >= 65 and PNEUVAC4 = 1,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
3,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Alabama,January,3062023,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,YesNotes: AGE >=65 and FLUSHOT7 = 1,YesNotes: AGE >= 65 and PNEUVAC4 = 1,YesNotes: HIVTST7 = 1,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
4,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Alabama,January,1062023,...,7,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,47,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,NoNotes: AGE >=65 and FLUSHOT7 = 2,YesNotes: AGE >= 65 and PNEUVAC4 = 1,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Have not driven after having too much to drink
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Virgin Islands,December,12112023,...,71,YesNotes: ALCDAY4<231 and 1<=DRNK3GE5<=76,1500,YesNotes: (SEXVAR=1) and _DRNKWK2 > 1400 or (S...,NoNotes: AGE >=65 and FLUSHOT7 = 2,NoNotes: AGE >= 65 and PNEUVAC4 = 2,YesNotes: HIVTST7 = 1,Always or Almost Always Wear Seat Belt,Don't Always Wear Seat Belt,Have not driven after having too much to drink
433319,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Virgin Islands,December,1032024,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,Age < 65,Age < 65Notes: AGE < 65,YesNotes: HIVTST7 = 1,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
433320,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Virgin Islands,December,12132023,...,3,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,47,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,Age < 65,Age < 65Notes: AGE < 65,YesNotes: HIVTST7 = 1,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Have not driven after having too much to drink
433321,NaN,NaN,NaN,4.0,NaN,NaN,NaN,Virgin Islands,December,12082023,...,No Drink-Occasions per dayNotes: ALCDAY4 = 888,NoNotes: ALCDAY4<231 and DRNK3GE5=88; or ALCDA...,Did not drinkNotes: DROCDY4_=0 or AVEDRNK3=88,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,NoNotes: AGE >=65 and FLUSHOT7 = 2,NoNotes: AGE >= 65 and PNEUVAC4 = 2,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Always Wear Seat Belt,Don't know/Not Sure/Refused/Missing
433322,NaN,NaN,NaN,7.0,1.0,NaN,NaN,Virgin Islands,December,12112023,...,67,YesNotes: ALCDAY4<231 and 1<=DRNK3GE5<=76,933,NoNotes: (SEXVAR=1) and _DRNKWK2 <= 1400 or (S...,Age < 65,Age < 65Notes: AGE < 65,NoNotes: HIVTST7 = 2,Always or Almost Always Wear Seat Belt,Don't Always Wear Seat Belt,Have not driven after having too much to drink

## 2 Dado tratado 

sem os indices que correspondem a strings que podem ser nulas como 

‘‘Don’t know/Not sure’’ and ‘‘Refused to answer,’’

In [24]:

def limpar_valores_indesejados_codebook(df_brfss, codebook_df, rotulos_invalidos):
    """
    Substitui por NaN os valores do DataFrame que correspondem a rótulos inválidos do codebook.

    Parâmetros:
        df_brfss (pd.DataFrame): dados originais com valores numéricos
        codebook_df (pd.DataFrame): codebook com colunas 'SAS Variable Name', 'Value', 'Value Label'
        rotulos_invalidos (list): lista de strings com rótulos que devem ser tratados como NaN

    Retorno:
        pd.DataFrame com valores substituídos por NaN onde os rótulos são inválidos
    """
    df_resultado = df_brfss.copy()

    for coluna in df_resultado.columns:
        try:
            codebook_var = codebook_df[codebook_df['SAS Variable Name'] == coluna]
            codebook_var = codebook_var.dropna(subset=['Value', 'Value Label'])

            # Filtra os valores que têm rótulos indesejados
            valores_invalidos = codebook_var[
                codebook_var['Value Label'].str.strip().isin(rotulos_invalidos)
            ]['Value']

            # Converte para float para comparar com os dados
            valores_invalidos_float = valores_invalidos.astype(float).tolist()

            # Substitui no dado
            df_resultado[coluna] = df_resultado[coluna].apply(
                lambda x: np.nan if x in valores_invalidos_float else x
            )

        except Exception as e:
            print(f"Erro ao processar coluna '{coluna}': {e}")
            continue

    return df_resultado

In [25]:
df_remove_string_index = df_2023.copy()
string_list_to_null = [["Refused","Don't know/Not Sure"]]
df_withhout_invalid = limpar_valores_indesejados_codebook(df_remove_string_index, codebook_2023, string_list_to_null)
df_withhout_invalid

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_FLSHOT7,_PNEUMO3,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,1.0,...,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,1.0,...,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,2.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,78.0,12.0,b'12112023',b'12',b'11',b'2023',1100.0,b'2023002064',2.023002e+09,NaN,...,7.100000e+01,2.0,1.500000e+03,2.0,2.0,2.0,1.0,1.0,2.0,2.0
433319,78.0,12.0,b'01032024',b'01',b'03',b'2024',1100.0,b'2023002065',2.023002e+09,NaN,...,5.397605e-79,1.0,5.397605e-79,1.0,NaN,NaN,1.0,1.0,1.0,9.0
433320,78.0,12.0,b'12132023',b'12',b'13',b'2023',1100.0,b'2023002066',2.023002e+09,NaN,...,3.000000e+00,1.0,4.700000e+01,1.0,NaN,NaN,1.0,1.0,1.0,2.0
433321,78.0,12.0,b'12082023',b'12',b'08',b'2023',1100.0,b'2023002067',2.023002e+09,NaN,...,5.397605e-79,1.0,5.397605e-79,1.0,2.0,2.0,2.0,1.0,1.0,9.0
433322,78.0,12.0,b'12112023',b'12',b'11',b'2023',1100.0,b'2023002068',2.023002e+09,NaN,...,6.700000e+01,2.0,9.330000e+02,1.0,NaN,NaN,2.0,1.0,2.0,2.0

Outros tratamentos de sctrings e dados de data

## 3 Tratamento de missing data 

(30% conforme o paper)

In [47]:
# Aplicar seleção de variáveis com menos de 25 % de missing após filtrar o Heart Attack and Stroke
# df_brfss_2023_filtered_columns_csv = pd.read_csv(f"{notebook_dir_project_predict}data{os.sep}intermediate{os.sep}2023{os.sep}brfss_2023.csv")
df_brfss_2023_filtered_columns_csv = df_withhout_invalid.copy()

# Calcular o percentual de valores nulos por coluna
percentual_na = df_brfss_2023_filtered_columns_csv.isnull().mean() * 100

# Selecionar colunas com menos de 30% de valores nulos - usar < 30
colunas_boas = percentual_na[percentual_na  < 30].index

# Criar novo DataFrame apenas com essas colunas
df_brfss_2023_csv_filtered = df_brfss_2023_filtered_columns_csv[colunas_boas]

# Exibir informações do DataFrame filtrado
df_brfss_2023_csv_filtered.info()

# Exibir o DataFrame
df_brfss_2023_csv_filtered

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 433323 entries, 0 to 433322
Columns: 152 entries, _STATE to _DRNKDRV
dtypes: float64(147), object(5)
memory usage: 502.5+ MB

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,SAFETIME,...,_CURECI2,DRNKANY6,DROCDY4_,_RFBING6,_DRNKWK2,_RFDRHV8,_AIDTST4,_RFSEAT2,_RFSEAT3,_DRNKDRV
0,1.0,1.0,b'03012023',b'03',b'01',b'2023',1100.0,b'2023000001',2.023000e+09,NaN,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,1.0,1.0,9.0
1,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000002',2.023000e+09,NaN,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,1.0,1.0,9.0
2,1.0,1.0,b'03082023',b'03',b'08',b'2023',1100.0,b'2023000003',2.023000e+09,NaN,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,1.0,1.0,9.0
3,1.0,1.0,b'03062023',b'03',b'06',b'2023',1100.0,b'2023000004',2.023000e+09,NaN,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,9.0
4,1.0,1.0,b'01062023',b'01',b'06',b'2023',1100.0,b'2023000005',2.023000e+09,NaN,...,1.0,1.0,7.000000e+00,1.0,4.700000e+01,1.0,2.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433318,78.0,12.0,b'12112023',b'12',b'11',b'2023',1100.0,b'2023002064',2.023002e+09,1.0,...,1.0,1.0,7.100000e+01,2.0,1.500000e+03,2.0,1.0,1.0,2.0,2.0
433319,78.0,12.0,b'01032024',b'01',b'03',b'2024',1100.0,b'2023002065',2.023002e+09,1.0,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,1.0,1.0,1.0,9.0
433320,78.0,12.0,b'12132023',b'12',b'13',b'2023',1100.0,b'2023002066',2.023002e+09,1.0,...,1.0,1.0,3.000000e+00,1.0,4.700000e+01,1.0,1.0,1.0,1.0,2.0
433321,78.0,12.0,b'12082023',b'12',b'08',b'2023',1100.0,b'2023002067',2.023002e+09,1.0,...,1.0,2.0,5.397605e-79,1.0,5.397605e-79,1.0,2.0,1.0,1.0,9.0
433322,78.0,12.0,b'12112023',b'12',b'11',b'2023',1100.0,b'2023002068',2.023002e+09,1.0,...,1.0,1.0,6.700000e+01,2.0,9.330000e+02,1.0,2.0,1.0,2.0,2.0